@api=http://localhost:3001/api/patients

### GET /
GET {{api}}

### GET /:id
GET {{api}}/d2773822-f723-11e9-8f0b-362b9e155667

### POST /
POST {{api}}
Content-Type: application/json
Accept: application/json

{
    "name": "Matti Luukkainen",
    "dateOfBirth": "1971-04-09",
    "ssn": "090471-8890",
    "gender": "male",
    "entries": [],
    "occupation": "Digital3"
}
