@api=http://localhost:3003/api

### GET api/blogs
GET {{api}}/blogs

### POST api/blogs
POST {{api}}/blogs
Content-Type: application/json

{
 "title": "Prueba 13",
 "author": "65d65b17cb6403cf2266b0e3",
 "url": "https://github.com/fernargdev",
 "likes": 13
}

### GET api/authors
GET  {{api}}/authors

### POST api/authors
POST {{api}}/authors
Content-Type: application/json

{
  "authorname": "Fernando3",
  "name": "Fernando Rodriguez",
  "password": "Salainen1"
}

### GET api/users
GET  {{api}}/users

### POST api/users
POST {{api}}/users
Content-Type: application/json

{
  "username": "xx",
  "name": "Arto Hellas",
  "password": "Fernando1234"
}

### DELETE api/users
DELETE {{api}}/users/65da10593cc6d6e0b35e05b6

 