@api=http://localhost:3003/api


# ### GET api/authors
# GET  {{api}}/authors

# ### POST api/authors
# POST {{api}}/authors
# Content-Type: application/json

# {
#   "authorname": "Fernando3",
#   "name": "Fernando Rodriguez",
#   "password": "Salainen1"
# }


### GET api/blogs
GET {{api}}/blogs

### POST api/blogs
POST {{api}}/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjVkYWU0MDBiZWNhYmNjNWI3M2Q2MzFhIiwiaWF0IjoxNzA4ODk3NzA0fQ.Htr6Z-zHFKYS738q1a9jzApNqj1pFe2fjFsa0v8NuTw

{
 "url": "https://martinfowler.com",
 "title": "Distributed Objects",
 "author": "Martin Fowler"
}

### DELETE api/blogs/id
DELETE {{api}}/blogs/65ddfa412a768fe2ac202dea
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjVkYWU0MDBiZWNhYmNjNWI3M2Q2MzFhIiwiaWF0IjoxNzA4ODk3NzA0fQ.Htr6Z-zHFKYS738q1a9jzApNqj1pFe2fjFsa0v8NuTw

### PUT api/blogs/id
PUT {{api}}/blogs


### GET api/users
GET  {{api}}/users

### POST api/users
POST {{api}}/users
Content-Type: application/json

{
  "username": "hellas",
  "name": "Arto Hellas",
  "password": "Fernando1234"
}

### DELETE api/users
DELETE {{api}}/users/65dad2b5c64ab064c14525ed


### POST api/login
POST {{api}}/login
Content-Type: application/json

{
  "username": "hellas",
  "password": "Fernando1234"
}

 